version: "3.9"

name: nchcsystem

networks:
  nchc:
    external: false
    
services:

  # nchc_nvflare:
    # container_name: nchc_nvflare
    # image: nvflare/nvflare
    # ports:
      # - 80:80
      # - 8003:8003
    # volumes:
      # - ./workspace:/workspace
      # - ./NVFlare-2.3:/NVFlare    
    # restart: always
    # networks:
      # - nchc    
    # extra_hosts:
      # - host.docker.internal:host-gateway
    # command: [ "sleep", "infinity" ]
    
  nchc_litellm:
    container_name: nchc_litellm
    #image: ghcr.io/berriai/litellm:main-latest
    image: c00cjz00/litellm:v2
    pull_policy: always    
    ports:
      - ${nchc_litellm}:4000
    volumes:
      - ./litellm/litellm-config.yaml:/app/config.yaml 
    restart: always
    healthcheck:
      test: curl -fs http://localhost:4000/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s 
    networks:
      - nchc
    depends_on:
      - nchc_postgres
    environment:
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}
    extra_hosts:
      - host.docker.internal:host-gateway
    command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8" ]

  nchc_postgres:
    container_name: nchc_postgres
    image: postgres:13.2-alpine
    ports:
      - ${nchc_postgres}:5432
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - nchc    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
 
  nchc_pgadmin4:
    container_name: nchc_pgadmin4
    image: dpage/pgadmin4:latest
    pull_policy: always    
    ports:
      - ${nchc_pgadmin4}:5080
    volumes:
      - ./storage/pgadmin:/var/lib/pgadmin
    restart: always
    networks:
      - nchc
    depends_on:
      - nchc_postgres       
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5080
    extra_hosts:
      - host.docker.internal:host-gateway

  nchc_php:
    container_name: nchc_php
    image: php:8.3-fpm
    pull_policy: always    
    ports:
      - ${nchc_php}:9000
    volumes:
      - ./website:/var/www/html      
    restart: always
    networks:
      - nchc     
    extra_hosts:
      - host.docker.internal:host-gateway
      
  nchc_nginx:
    container_name: nchc_nginx
    image: nginx
    ports:
      -  ${nchc_nginx_443}:443
    volumes:
      - ./nginx/biobank_ssl:/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
      - ./nginx/litellm.conf:/etc/nginx/conf.d/litellm.conf
      - ./nginx/pgadmin4.conf:/etc/nginx/conf.d/pgadmin4.conf
      - ./website:/var/www/html  
    restart: always
    networks:
        - nchc
    extra_hosts:
      - host.docker.internal:host-gateway

  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

